M48
; DRILL file {KiCad 7.0.7+dfsg-1} date Πεμ 02 Μαΐ 2024 01:52:29 μμ EEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-02T13:52:29+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X3.6419Y-2.9591
X3.6419Y-3.9709
X3.6419Y-4.9276
X3.6419Y-6.0575
T0
M30
